server:
  port: 9000
token:
  expiration-time: 2592000000 #token失效时间一个月 1000 * 60 * 60 * 24 * 30
  secret: wuwenqiang #token秘钥
app:
  appId: com.play.user
  appName: 用户中心
spring:
  application:
    name: player-user
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/play?characterEncoding=utf-8
      username: root
      password: wwq_2021
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
#mybatis:
#  mapper-locations: classpath:mapper/*Mapper.xml

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.player.user.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: http://localhost:4001/eureka/,http://localhost:4002/eureka/
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #指定实例id